---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
  namespace: default
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: allow-ping-c
spec:
    ingress:
    - action: allow
      source:
        selector: app == 'ping-c'
    
---
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: allow-ping-3
spec:
    ingress:
    - action: allow
      source:
        selector: app == 'ping-3'